import {
  Resident,
  Contribution,
  Expense,
  MaintenanceShift,
  Incident,
  CommunitySettings,
  UserAccount,
  IndertDocument,
  LandRequest,
  CommunityPost,
} from '../types';
import { generateSampleCIDocument } from '../utils/ciGenerator';

export const initialSettings: CommunitySettings = {
  appName: 'S16 - Gestión Comunitaria INDERT',
  communityName: 'Comisión Vecinal Pro-Tierra Asentamiento "Sector 16 - Esperanza"',
  settlementLocation: 'Colonia Quebrada Alta, Parcela 14-B (Exp. INDERT)',
  currencySymbol: 'Gs.',
  monthlyGeneralFee: 50000,
  presidentName: 'Carlos Mendoza Ramos',
  treasurerName: 'Marta Delgado Silva',
  secretaryName: 'Lic. Rodrigo Benítez',
  contactPhone: '+595981234567',
  emergencyPhone: '+595981998877',
  indertExpedienteNumber: 'Exp. INDERT N° 4821/2024',
  adminPolicies: {
    requireTreasuryDoubleCheck: true,
    requireOverlapConfirmation: true,
    requireRelocationActNumber: true,
    confirmDeletionResidents: true,
    confirmDeletionIndertDocs: true,
    allowPublicSelfRegistration: true,
    moderateCommunityPosts: false,
    autoLogAbsenceFine: true,
    defaultAbsenceFineAmount: 30000,
  },
  googleAuth: {
    enabled: true,
    clientId: '307245872155-s16community.apps.googleusercontent.com',
    allowedDomains: 'gmail.com, indert.gov.py, *',
    adminGoogleEmail: 'servernogardpy@gmail.com',
    autoLinkWithDocumentId: true,
    lastConnectionTestStatus: 'connected',
    lastConnectionTestMessage: 'Servicio de Google Identity listo y habilitado para inicio de sesión en Sector 16.',
    lastTestedAt: '2026-09-08 04:30',
  },
};

export const initialResidents: Resident[] = [
  {
    id: 'res-1',
    fullName: 'Juan Bautista Benítez',
    documentId: '4.892.110',
    phone: '+595981112233',
    barrio: 'Sector 16',
    block: 'A',
    lot: '01',
    sector: 'Entrada Principal',
    occupationDate: '2023-03-15',
    status: 'active',
    familyMembersCount: 4,
    maritalStatus: 'casado',
    hasPartner: true,
    partnerName: 'Romina Soledad Candia',
    partnerDocumentId: '4.912.441',
    childrenCount: 2,
    hasChildrenWithDisability: false,
    disabilityDetails: '',
    documentFrontUrl: generateSampleCIDocument('Juan Bautista Benítez', '4.892.110', 'frente', {
      maritalStatus: 'CASADO',
    }),
    documentBackUrl: generateSampleCIDocument('Juan Bautista Benítez', '4.892.110', 'dorso'),
    previousSettlementHistory: 'Sin registros previos en otras comunidades. Primer terreno adjudicado.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Vivienda construida con material prefabricado. Delegado de la Manzana A.',
  },
  {
    id: 'res-2',
    fullName: 'María Elena González Acosta',
    documentId: '3.450.982',
    phone: '+595982334455',
    barrio: 'Sector 16',
    block: 'A',
    lot: '02',
    sector: 'Entrada Principal',
    occupationDate: '2023-04-10',
    status: 'active',
    familyMembersCount: 3,
    maritalStatus: 'concubinato',
    hasPartner: true,
    partnerName: 'Pedro Ignacio Benítez',
    partnerDocumentId: '3.210.871',
    childrenCount: 1,
    hasChildrenWithDisability: true,
    disabilityDetails: 'Hijo menor con parálisis cerebral leve. Requiere acceso nivelado para silla de ruedas.',
    documentFrontUrl: generateSampleCIDocument('María Elena González Acosta', '3.450.982', 'frente', {
      maritalStatus: 'UNIÓN DE HECHO',
    }),
    documentBackUrl: generateSampleCIDocument('María Elena González Acosta', '3.450.982', 'dorso'),
    previousSettlementHistory: 'Residió anteriormente como inquilina en Barrio Obrero. Verificado por asamblea vecinal.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Puntual en faenas comunitarias. Cuotas al día.',
  },
  {
    id: 'res-3',
    fullName: 'Roberto Darío Franco Méndez',
    documentId: '5.120.443',
    phone: '+595983556677',
    barrio: 'Sector 16',
    block: 'A',
    lot: '03',
    sector: 'Entrada Principal',
    occupationDate: '2023-06-01',
    status: 'flagged',
    familyMembersCount: 2,
    maritalStatus: 'soltero',
    hasPartner: false,
    childrenCount: 0,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Roberto Darío Franco Méndez', '5.120.443', 'frente', {
      maritalStatus: 'SOLTERO',
    }),
    documentBackUrl: generateSampleCIDocument('Roberto Darío Franco Méndez', '5.120.443', 'dorso'),
    previousSettlementHistory: 'ADVERTENCIA: Figura registrado en censo de Asentamiento "Nuevo Amanecer" (2021) del cual fue desalojado por intentar revender lote asignado.',
    isFraudRisk: true,
    fraudNotes: 'Sospecha de tráfico de lotes. Se le exige presencia permanente y prohibición expresa de cesión o alquiler.',
    notes: 'Debe cuotas de luz de los últimos 2 meses.',
  },
  {
    id: 'res-4',
    fullName: 'Clara Rosa Giménez de López',
    documentId: '2.998.712',
    phone: '+595984778899',
    barrio: 'Sector 16',
    block: 'B',
    lot: '01',
    sector: 'Sector Tanque de Agua',
    occupationDate: '2023-05-20',
    status: 'active',
    familyMembersCount: 5,
    maritalStatus: 'viudo',
    hasPartner: false,
    childrenCount: 3,
    hasChildrenWithDisability: true,
    disabilityDetails: 'Hija adolescente con hipoacusia neurosensorial bilateral (discapacidad auditiva).',
    documentFrontUrl: generateSampleCIDocument('Clara Rosa Giménez de López', '2.998.712', 'frente', {
      maritalStatus: 'VIUDA',
    }),
    documentBackUrl: generateSampleCIDocument('Clara Rosa Giménez de López', '2.998.712', 'dorso'),
    previousSettlementHistory: 'Familia reubicada por riesgo de inundación en zona ribereña. Certificado social presentado.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Madre viuda sostén de hogar. Colabora activamente en el comedor vecinal.',
  },
  {
    id: 'res-5',
    fullName: 'Ignacio Javier Paredes',
    documentId: '4.321.890',
    phone: '+595985990011',
    barrio: 'Sector 16',
    block: 'B',
    lot: '02',
    sector: 'Sector Tanque de Agua',
    occupationDate: '2023-07-12',
    status: 'active',
    familyMembersCount: 3,
    maritalStatus: 'casado',
    hasPartner: true,
    partnerName: 'Silvia Beatriz Vera',
    partnerDocumentId: '4.551.209',
    childrenCount: 1,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Ignacio Javier Paredes', '4.321.890', 'frente', {
      maritalStatus: 'CASADO',
    }),
    documentBackUrl: generateSampleCIDocument('Ignacio Javier Paredes', '4.321.890', 'dorso'),
    previousSettlementHistory: 'Sin antecedentes negativos.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Electricista de oficio. Ayuda en el cableado comunal.',
  },
  {
    id: 'res-6',
    fullName: 'Estela Maris Cabrera Ortiz',
    documentId: '3.876.541',
    phone: '+595986112244',
    barrio: 'Sector 16',
    block: 'B',
    lot: '03',
    sector: 'Sector Tanque de Agua',
    occupationDate: '2023-08-05',
    status: 'active',
    familyMembersCount: 4,
    maritalStatus: 'casado',
    hasPartner: true,
    partnerName: 'Miguel Ángel Bogarín',
    partnerDocumentId: '3.621.908',
    childrenCount: 2,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Estela Maris Cabrera Ortiz', '3.876.541', 'frente', {
      maritalStatus: 'CASADA',
    }),
    documentBackUrl: generateSampleCIDocument('Estela Maris Cabrera Ortiz', '3.876.541', 'dorso'),
    previousSettlementHistory: 'Previamente censada en Terreno San Roque como copropietaria legítima con acta de entrega formal.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Pagó aporte extraordinario para compra de bomba de agua.',
  },
  {
    id: 'res-7',
    fullName: 'Víctor Hugo Samudio',
    documentId: '5.643.209',
    phone: '+595987334466',
    barrio: 'Sector 16',
    block: 'C',
    lot: '01',
    sector: 'Sector Quebrada',
    occupationDate: '2023-09-18',
    status: 'flagged',
    familyMembersCount: 1,
    maritalStatus: 'soltero',
    hasPartner: false,
    childrenCount: 0,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Víctor Hugo Samudio', '5.643.209', 'frente', {
      maritalStatus: 'SOLTERO',
    }),
    documentBackUrl: generateSampleCIDocument('Víctor Hugo Samudio', '5.643.209', 'dorso'),
    previousSettlementHistory: 'ALERTA ROJA: Detectado registro simultáneo en Asentamiento "San Blas" Lote 8 Mz 4 con la misma C.I. No habita el lote de manera continua.',
    isFraudRisk: true,
    fraudNotes: 'Posible acaparamiento ilegal de terrenos. Asunto elevado a la Comisión Directiva para dictamen.',
    notes: 'Tiene 3 cuotas pendientes de agua y luz. Pendiente notificación formal.',
  },
  {
    id: 'res-8',
    fullName: 'Gloria Concepción Duarte',
    documentId: '4.109.873',
    phone: '+595988556688',
    barrio: 'Sector 16',
    block: 'C',
    lot: '02',
    sector: 'Sector Quebrada',
    occupationDate: '2023-10-02',
    status: 'active',
    familyMembersCount: 6,
    maritalStatus: 'concubinato',
    hasPartner: true,
    partnerName: 'Dionisio Ramón Silva',
    partnerDocumentId: '4.011.890',
    childrenCount: 4,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Gloria Concepción Duarte', '4.109.873', 'frente', {
      maritalStatus: 'UNIÓN DE HECHO',
    }),
    documentBackUrl: generateSampleCIDocument('Gloria Concepción Duarte', '4.109.873', 'dorso'),
    previousSettlementHistory: 'Sin registros de ocupación irregular previa.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Comité de vigilancia vecinal.',
  },
  {
    id: 'res-9',
    fullName: 'Armando Ramón Rolón',
    documentId: '3.754.218',
    phone: '+595989778800',
    barrio: 'Sector 16',
    block: 'C',
    lot: '03',
    sector: 'Sector Quebrada',
    occupationDate: '2024-01-14',
    status: 'active',
    familyMembersCount: 2,
    maritalStatus: 'divorciado',
    hasPartner: false,
    childrenCount: 1,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Armando Ramón Rolón', '3.754.218', 'frente', {
      maritalStatus: 'DIVORCIADO',
    }),
    documentBackUrl: generateSampleCIDocument('Armando Ramón Rolón', '3.754.218', 'dorso'),
    previousSettlementHistory: 'Sin antecedentes.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Conductor de camión de flete.',
  },
  {
    id: 'res-10',
    fullName: 'Lorenzo Vera Bogado',
    documentId: '2.845.671',
    phone: '+595981223344',
    barrio: 'Sector 16',
    block: 'D',
    lot: '01',
    sector: 'Sector Alto Límite',
    occupationDate: '2024-02-28',
    status: 'transferred',
    familyMembersCount: 3,
    maritalStatus: 'casado',
    hasPartner: true,
    partnerName: 'Ana María Gómez',
    partnerDocumentId: '2.901.124',
    childrenCount: 2,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Lorenzo Vera Bogado', '2.845.671', 'frente', {
      maritalStatus: 'CASADO',
    }),
    documentBackUrl: generateSampleCIDocument('Lorenzo Vera Bogado', '2.845.671', 'dorso'),
    previousSettlementHistory: 'Traspaso documentado y certificado por escribanía comunal al titular actual.',
    isFraudRisk: false,
    fraudNotes: '',
    notes: 'Lote traspasado con anuencia de la asamblea.',
  },
];

export const initialContributions: Contribution[] = [
  {
    id: 'con-1',
    residentId: 'res-1',
    residentName: 'Juan Bautista Benítez',
    documentId: '4.892.110',
    block: 'A',
    lot: '01',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Septiembre 2026',
    amount: 50000,
    amountPaid: 50000,
    month: '2026-09',
    date: '2026-09-02',
    receiptNumber: 'REC-2026-089',
    paymentMethod: 'efectivo',
    status: 'paid',
  },
  {
    id: 'con-2',
    residentId: 'res-1',
    residentName: 'Juan Bautista Benítez',
    documentId: '4.892.110',
    block: 'A',
    lot: '01',
    category: 'agua',
    concept: 'Cuota Cisterna de Agua Potable - Septiembre 2026',
    amount: 30000,
    amountPaid: 30000,
    month: '2026-09',
    date: '2026-09-02',
    receiptNumber: 'REC-2026-090',
    paymentMethod: 'efectivo',
    status: 'paid',
  },
  {
    id: 'con-3',
    residentId: 'res-2',
    residentName: 'María Elena González Acosta',
    documentId: '3.450.982',
    block: 'A',
    lot: '02',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Septiembre 2026',
    amount: 50000,
    amountPaid: 50000,
    month: '2026-09',
    date: '2026-09-03',
    receiptNumber: 'REC-2026-091',
    paymentMethod: 'transferencia',
    status: 'paid',
  },
  {
    id: 'con-4',
    residentId: 'res-2',
    residentName: 'María Elena González Acosta',
    documentId: '3.450.982',
    block: 'A',
    lot: '02',
    category: 'agua',
    concept: 'Cuota Cisterna de Agua Potable - Septiembre 2026',
    amount: 30000,
    amountPaid: 30000,
    month: '2026-09',
    date: '2026-09-03',
    receiptNumber: 'REC-2026-092',
    paymentMethod: 'transferencia',
    status: 'paid',
  },
  {
    id: 'con-5',
    residentId: 'res-3',
    residentName: 'Roberto Darío Franco Méndez',
    documentId: '5.120.443',
    block: 'A',
    lot: '03',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Septiembre 2026',
    amount: 50000,
    amountPaid: 0,
    month: '2026-09',
    date: '2026-09-01',
    receiptNumber: 'PEND-001',
    paymentMethod: 'efectivo',
    status: 'pending',
    notes: 'Notificado el 03/09. Aún no se acercó a tesorería.',
  },
  {
    id: 'con-6',
    residentId: 'res-3',
    residentName: 'Roberto Darío Franco Méndez',
    documentId: '5.120.443',
    block: 'A',
    lot: '03',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Agosto 2026 (Atraso)',
    amount: 50000,
    amountPaid: 0,
    month: '2026-08',
    date: '2026-08-01',
    receiptNumber: 'PEND-002',
    paymentMethod: 'efectivo',
    status: 'pending',
    notes: 'Mora acumulada mes anterior.',
  },
  {
    id: 'con-7',
    residentId: 'res-4',
    residentName: 'Clara Rosa Giménez de López',
    documentId: '2.998.712',
    block: 'B',
    lot: '01',
    category: 'agua',
    concept: 'Cuota Cisterna de Agua Potable - Septiembre 2026',
    amount: 30000,
    amountPaid: 30000,
    month: '2026-09',
    date: '2026-09-01',
    receiptNumber: 'REC-2026-093',
    paymentMethod: 'efectivo',
    status: 'paid',
  },
  {
    id: 'con-8',
    residentId: 'res-5',
    residentName: 'Ignacio Javier Paredes',
    documentId: '4.321.890',
    block: 'B',
    lot: '02',
    category: 'mantenimiento',
    concept: 'Fondo Reparación Cableado Principal Manzana B',
    amount: 40000,
    amountPaid: 40000,
    month: '2026-09',
    date: '2026-09-02',
    receiptNumber: 'REC-2026-094',
    paymentMethod: 'efectivo',
    status: 'paid',
  },
  {
    id: 'con-9',
    residentId: 'res-6',
    residentName: 'Estela Maris Cabrera Ortiz',
    documentId: '3.876.541',
    block: 'B',
    lot: '03',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Septiembre 2026',
    amount: 50000,
    amountPaid: 50000,
    month: '2026-09',
    date: '2026-09-02',
    receiptNumber: 'REC-2026-095',
    paymentMethod: 'transferencia',
    status: 'paid',
  },
  {
    id: 'con-10',
    residentId: 'res-6',
    residentName: 'Estela Maris Cabrera Ortiz',
    documentId: '3.876.541',
    block: 'B',
    lot: '03',
    category: 'extraordinario',
    concept: 'Aporte Pozo Artesiano Comunitario INDERT',
    amount: 100000,
    amountPaid: 100000,
    month: '2026-08',
    date: '2026-08-28',
    receiptNumber: 'REC-2026-096',
    paymentMethod: 'transferencia',
    status: 'paid',
  },
  {
    id: 'con-11',
    residentId: 'res-7',
    residentName: 'Víctor Hugo Samudio',
    documentId: '5.643.209',
    block: 'C',
    lot: '01',
    category: 'agua',
    concept: 'Cuota Cisterna de Agua Potable - Septiembre 2026',
    amount: 30000,
    amountPaid: 0,
    month: '2026-09',
    date: '2026-09-01',
    receiptNumber: 'PEND-003',
    paymentMethod: 'efectivo',
    status: 'pending',
    notes: 'No habita permanentemente el lote.',
  },
  {
    id: 'con-12',
    residentId: 'res-7',
    residentName: 'Víctor Hugo Samudio',
    documentId: '5.643.209',
    block: 'C',
    lot: '01',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Septiembre 2026',
    amount: 50000,
    amountPaid: 0,
    month: '2026-09',
    date: '2026-09-01',
    receiptNumber: 'PEND-004',
    paymentMethod: 'efectivo',
    status: 'pending',
  },
  {
    id: 'con-13',
    residentId: 'res-8',
    residentName: 'Gloria Concepción Duarte',
    documentId: '4.109.873',
    block: 'C',
    lot: '02',
    category: 'luz',
    concept: 'Aporte Luz Comunitaria - Septiembre 2026',
    amount: 50000,
    amountPaid: 50000,
    month: '2026-09',
    date: '2026-09-02',
    receiptNumber: 'REC-2026-097',
    paymentMethod: 'transferencia',
    status: 'paid',
  },
  {
    id: 'con-14',
    residentId: 'res-9',
    residentName: 'Armando Ramón Rolón',
    documentId: '3.754.218',
    block: 'C',
    lot: '03',
    category: 'agua',
    concept: 'Cuota Cisterna de Agua Potable - Septiembre 2026',
    amount: 30000,
    amountPaid: 20000,
    month: '2026-09',
    date: '2026-09-04',
    receiptNumber: 'REC-2026-098',
    paymentMethod: 'efectivo',
    status: 'partial',
    notes: 'Abono parcial de Gs. 20.000. Saldo restante de Gs. 10.000 pendiente.',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    category: 'luz',
    title: 'Factura Mensual Medidor Comunitario ANDE / Luz',
    description: 'Pago de consumo global del transformador y medidor general que abastece las 4 manzanas.',
    amount: 650000,
    date: '2026-09-04',
    month: '2026-09',
    supplierOrPayee: 'Administración Nacional de Electricidad (ANDE Factura #88219)',
    receiptOrInvoice: 'FAC-ANDE-88219',
    status: 'paid',
    paidByTreasurer: 'Marta Delgado Silva',
  },
  {
    id: 'exp-2',
    category: 'agua',
    title: '2 Camiones Cisterna de Agua Potable (10.000 L c/u)',
    description: 'Llenado de tanques comunitarios para distribución semanal de los residentes del Sector 16.',
    amount: 450000,
    date: '2026-09-03',
    month: '2026-09',
    supplierOrPayee: 'Cisterna y Transporte "El Chaco"',
    receiptOrInvoice: 'FAC-B-00341',
    status: 'paid',
    paidByTreasurer: 'Marta Delgado Silva',
  },
  {
    id: 'exp-3',
    category: 'caminos',
    title: 'Alquiler de Motoniveladora y Ripio para Acceso Principal',
    description: 'Nivelación de 400 metros de calle principal tras fuertes lluvias de agosto.',
    amount: 850000,
    date: '2026-08-25',
    month: '2026-08',
    supplierOrPayee: 'Servicios Viales del Sur S.A.',
    receiptOrInvoice: 'FAC-A-001294',
    status: 'paid',
    paidByTreasurer: 'Marta Delgado Silva',
  },
  {
    id: 'exp-4',
    category: 'agua',
    title: 'Cañerías de 2 Pulgadas y Accesorios Red de Distribución',
    description: 'Compra de 20 tubos PVC y llaves de paso para extensión a Manzana C.',
    amount: 620000,
    date: '2026-08-10',
    month: '2026-08',
    supplierOrPayee: 'Ferretería & Sanitaria San Roque S.R.L.',
    receiptOrInvoice: 'FAC-001-002-004812',
    status: 'paid',
    paidByTreasurer: 'Marta Delgado Silva',
  },
  {
    id: 'exp-5',
    category: 'legal',
    title: 'Honorarios Topógrafo e Informe Técnico INDERT',
    description: 'Levantamiento planimétrico y colocación de mojones georreferenciados para expediente 4821/2024.',
    amount: 1450000,
    date: '2026-07-22',
    month: '2026-07',
    supplierOrPayee: 'Ing. Agrimensor Carlos Aranda (Reg. 8421)',
    receiptOrInvoice: 'FAC-002-001-009182',
    status: 'paid',
    paidByTreasurer: 'Marta Delgado Silva',
  },
  {
    id: 'exp-6',
    category: 'seguridad',
    title: 'Reflectores LED Solares para Esquinas Comunitarias',
    description: 'Instalación de 4 luminarias solares en los cruces de calles principales.',
    amount: 380000,
    date: '2026-08-15',
    month: '2026-08',
    supplierOrPayee: 'Iluminación Paraguaya Import',
    receiptOrInvoice: 'REC-0941',
    status: 'paid',
    paidByTreasurer: 'Marta Delgado Silva',
  },
];

export const initialShifts: MaintenanceShift[] = [
  {
    id: 'shift-1',
    taskTitle: 'Limpieza y Desmalezado de Calle Principal',
    taskCategory: 'limpieza',
    assignedResidentId: 'res-1',
    assignedResidentName: 'Juan Bautista Benítez',
    block: 'A',
    lot: '01',
    dateScheduled: '2026-09-07',
    timeSlot: '07:30 - 11:30',
    status: 'completed',
    completionNotes: 'Cumplió faena completa. Retiró ramas y maleza de la calzada principal.',
    completedAt: '2026-09-07 11:45',
  },
  {
    id: 'shift-2',
    taskTitle: 'Mantenimiento del Pozo Comunitario y Válvulas de Agua',
    taskCategory: 'zanjas_agua',
    assignedResidentId: 'res-2',
    assignedResidentName: 'María Elena González Acosta',
    block: 'A',
    lot: '02',
    dateScheduled: '2026-09-08',
    timeSlot: '08:00 - 12:00',
    status: 'scheduled',
  },
  {
    id: 'shift-3',
    taskTitle: 'Vigilancia Nocturna y Control de Ingreso Vecinal',
    taskCategory: 'vigilancia',
    assignedResidentId: 'res-3',
    assignedResidentName: 'Roberto Darío Franco Méndez',
    block: 'A',
    lot: '03',
    dateScheduled: '2026-09-05',
    timeSlot: '20:00 - 00:00',
    status: 'absent',
    completionNotes: 'No se presentó a la faena comunitaria sin aviso previo.',
    fineAmount: 50000,
  },
  {
    id: 'shift-4',
    taskTitle: 'Apertura de Zanja para Caño de Desagüe Pluvial',
    taskCategory: 'zanjas_agua',
    assignedResidentId: 'res-5',
    assignedResidentName: 'Ignacio Javier Paredes',
    block: 'B',
    lot: '02',
    dateScheduled: '2026-09-09',
    timeSlot: '07:30 - 11:30',
    status: 'scheduled',
  },
  {
    id: 'shift-5',
    taskTitle: 'Revisión y Ajuste de Conexiones Eléctricas Bajas',
    taskCategory: 'electrico',
    assignedResidentId: 'res-5',
    assignedResidentName: 'Ignacio Javier Paredes',
    block: 'B',
    lot: '02',
    dateScheduled: '2026-09-02',
    timeSlot: '14:00 - 18:00',
    status: 'completed',
    completionNotes: 'Elevó cables que rozaban ramas sobre callejon Manzana B.',
    completedAt: '2026-09-02 18:10',
  },
  {
    id: 'shift-6',
    taskTitle: 'Faena General: Poda y Limpieza Alrededor del Tanque',
    taskCategory: 'faena_general',
    assignedResidentId: 'res-6',
    assignedResidentName: 'Estela Maris Cabrera Ortiz',
    block: 'B',
    lot: '03',
    dateScheduled: '2026-09-10',
    timeSlot: '08:00 - 12:00',
    status: 'scheduled',
  },
  {
    id: 'shift-7',
    taskTitle: 'Vigilancia y Rondas Preventivas Sector Quebrada',
    taskCategory: 'vigilancia',
    assignedResidentId: 'res-8',
    assignedResidentName: 'Gloria Concepción Duarte',
    block: 'C',
    lot: '02',
    dateScheduled: '2026-09-04',
    timeSlot: '18:00 - 22:00',
    status: 'completed',
    completionNotes: 'Ronda completada sin novedades.',
    completedAt: '2026-09-04 22:15',
  },
];

export const initialIncidents: Incident[] = [
  {
    id: 'inc-1',
    title: 'Fuga de agua en llave matriz que conecta Manzanas A y B',
    description: 'Se rompió un codo de PVC de 2 pulgadas frente al lote A-02 provocando pérdida continua de agua potable.',
    category: 'agua_fuga',
    reportedByName: 'María Elena González',
    reportedByResidentId: 'res-2',
    block: 'A',
    lot: '02',
    reportedDate: '2026-09-06',
    priority: 'urgente',
    status: 'en_proceso',
    assignedTo: 'Ignacio Paredes (Electricista/Plomero)',
  },
  {
    id: 'inc-2',
    title: 'Intento de cercado irregular en área de reserva de plaza',
    description: 'Personas desconocidas intentaron clavar postes de madera en la esquina de la Manzana C reservada para futura escuela y plaza pública.',
    category: 'intento_invasion',
    reportedByName: 'Juan Bautista Benítez',
    reportedByResidentId: 'res-1',
    block: 'C',
    lot: '01',
    reportedDate: '2026-09-04',
    priority: 'urgente',
    status: 'en_proceso',
    resolutionNotes: 'La comisión vecinal intervino inmediatamente y labró acta con testigos.',
    assignedTo: 'Carlos Mendoza (Presidente)',
  },
  {
    id: 'inc-3',
    title: 'Corte intermitente por sobrecarga en transformador secundario',
    description: 'Tras conexión de 2 soldadoras en la Manzana D, saltó la térmica general varias veces durante la tarde.',
    category: 'luz_corte',
    reportedByName: 'Lorenzo Vera Bogado',
    reportedByResidentId: 'res-10',
    block: 'D',
    lot: '01',
    reportedDate: '2026-09-03',
    priority: 'alta',
    status: 'resuelta',
    resolutionNotes: 'Se notificó a los talleres no conectar maquinaria pesada sin regulador.',
    resolvedAt: '2026-09-04 10:00',
  },
];

export const initialUsers: UserAccount[] = [
  {
    id: 'user-admin',
    username: 'admin',
    documentId: 'admin',
    fullName: 'Administrador General',
    phone: '+595981234567',
    email: 'admin@sector16.org.py',
    role: 'admin',
    customRoleTitle: 'Presidente / Admin General',
    password: 'Team-Nogardd123',
    permissions: {
      canManageUsers: true,
      canManageFinances: true,
      canManageResidents: true,
      canManageLandRequests: true,
      canManageIndertDocs: true,
      canManageShifts: true,
      canManageIncidents: true,
      canExportReports: true,
    },
    barrio: 'Sector 16',
    block: 'A',
    lot: 'Admin',
    createdAt: '2023-01-10',
    lastLogin: '2026-09-06 20:42',
    avatarColor: 'bg-blue-600',
    authProvider: 'local',
  },
  {
    id: 'user-google-main',
    username: 'google-admin',
    documentId: '4.892.110',
    fullName: 'Usuario Principal (Google)',
    phone: '+595981112233',
    email: 'servernogardpy@gmail.com',
    role: 'admin',
    customRoleTitle: 'Presidente / Admin',
    password: 'Team-Nogardd123',
    permissions: {
      canManageUsers: true,
      canManageFinances: true,
      canManageResidents: true,
      canManageLandRequests: true,
      canManageIndertDocs: true,
      canManageShifts: true,
      canManageIncidents: true,
      canExportReports: true,
    },
    barrio: 'Sector 16',
    block: 'A',
    lot: '01',
    residentId: 'res-1',
    createdAt: '2023-03-15',
    lastLogin: '2026-09-06 15:40',
    avatarColor: 'bg-amber-600',
    authProvider: 'google',
  },
  {
    id: 'user-carlos-mendoza',
    username: 'carlos.mendoza',
    documentId: '2.145.980',
    fullName: 'Carlos Mendoza Ramos',
    phone: '+595981234567',
    email: 'carlos.mendoza@s16.org.py',
    role: 'admin',
    customRoleTitle: 'Presidente de Comisión',
    password: 'Team-Nogardd123',
    permissions: {
      canManageUsers: true,
      canManageFinances: true,
      canManageResidents: true,
      canManageLandRequests: true,
      canManageIndertDocs: true,
      canManageShifts: true,
      canManageIncidents: true,
      canExportReports: true,
    },
    barrio: 'Sector 16',
    block: 'A',
    lot: 'Admin',
    createdAt: '2023-01-10',
    lastLogin: '2026-09-06 08:30',
    avatarColor: 'bg-blue-600',
    authProvider: 'local',
  },
  {
    id: 'user-directiva',
    documentId: '3.190.224',
    fullName: 'Marta Delgado Silva',
    phone: '+595981778899',
    email: 'marta.tesoreria@s16.org.py',
    role: 'tesorera',
    customRoleTitle: 'Tesorera Comunal Titular',
    permissions: {
      canManageUsers: false,
      canManageFinances: true,
      canManageResidents: false,
      canManageLandRequests: false,
      canManageIndertDocs: true,
      canManageShifts: false,
      canManageIncidents: false,
      canExportReports: true,
    },
    barrio: 'Sector 16',
    block: 'B',
    lot: '01',
    createdAt: '2023-01-15',
    lastLogin: '2026-09-05 19:15',
    avatarColor: 'bg-emerald-600',
    authProvider: 'local',
  },
  {
    id: 'user-secretaria',
    documentId: '2.845.109',
    fullName: 'Sandra Rivas Duarte',
    phone: '+595983445566',
    email: 'sandra.actas@s16.org.py',
    role: 'secretaria',
    customRoleTitle: 'Secretaría de Actas',
    permissions: {
      canManageUsers: false,
      canManageFinances: false,
      canManageResidents: true,
      canManageLandRequests: true,
      canManageIndertDocs: true,
      canManageShifts: true,
      canManageIncidents: true,
      canExportReports: true,
    },
    barrio: 'Sector 16',
    block: 'A',
    lot: '05',
    createdAt: '2023-02-20',
    lastLogin: '2026-09-05 14:20',
    avatarColor: 'bg-indigo-600',
    authProvider: 'local',
  },
  {
    id: 'user-delegado-a',
    documentId: '3.890.412',
    fullName: 'Antonio Romero Acosta',
    phone: '+595972889900',
    email: 'antonio.romero@s16.org.py',
    role: 'delegado',
    customRoleTitle: 'Delegado Manzana A',
    assignedBlock: 'A',
    permissions: {
      canManageUsers: false,
      canManageFinances: false,
      canManageResidents: false,
      canManageLandRequests: false,
      canManageIndertDocs: false,
      canManageShifts: true,
      canManageIncidents: true,
      canExportReports: false,
    },
    barrio: 'Sector 16',
    block: 'A',
    lot: '08',
    createdAt: '2023-04-12',
    lastLogin: '2026-09-04 18:10',
    avatarColor: 'bg-orange-600',
    authProvider: 'local',
  },
  {
    id: 'user-sindico',
    documentId: '1.980.552',
    fullName: 'Don Cecilio Benítez',
    phone: '+595985112244',
    email: 'cecilio.sindico@s16.org.py',
    role: 'sindico',
    customRoleTitle: 'Síndico Fiscalizador',
    permissions: {
      canManageUsers: false,
      canManageFinances: false,
      canManageResidents: false,
      canManageLandRequests: false,
      canManageIndertDocs: false,
      canManageShifts: false,
      canManageIncidents: false,
      canExportReports: true,
    },
    barrio: 'Sector 16',
    block: 'C',
    lot: '02',
    createdAt: '2023-01-20',
    lastLogin: '2026-09-03 11:00',
    avatarColor: 'bg-cyan-600',
    authProvider: 'local',
  },
  {
    id: 'user-res-1',
    documentId: '4.892.110',
    fullName: 'Juan Bautista Benítez',
    phone: '+595981112233',
    email: 'juan.benitez@gmail.com',
    role: 'residente',
    customRoleTitle: 'Vecino Censado',
    barrio: 'Sector 16',
    block: 'A',
    lot: '01',
    residentId: 'res-1',
    createdAt: '2023-03-15',
    lastLogin: '2026-09-06 10:12',
    avatarColor: 'bg-slate-600',
    authProvider: 'local',
  },
  {
    id: 'user-res-2',
    documentId: '3.450.982',
    fullName: 'María Elena González Acosta',
    phone: '+595982334455',
    email: 'maria.gonzalez@gmail.com',
    role: 'residente',
    customRoleTitle: 'Vecina Censada',
    barrio: 'Sector 16',
    block: 'A',
    lot: '02',
    residentId: 'res-2',
    createdAt: '2023-04-10',
    lastLogin: '2026-09-04 16:40',
    avatarColor: 'bg-pink-600',
    authProvider: 'local',
  },
];

export const initialIndertDocuments: IndertDocument[] = [
  {
    id: 'doc-indert-1',
    title: 'Expediente Matriz INDERT N° 4821/2024 - Solicitud de Adjudicación Comunitaria',
    category: 'expediente_indert',
    documentNumber: 'Exp. INDERT N° 4821/2024',
    date: '2024-03-12',
    uploadedBy: 'Carlos Mendoza (Presidente)',
    fileType: 'pdf',
    fileName: 'Expediente_Matriz_INDERT_4821_2024.pdf',
    fileSize: '3.4 MB',
    status: 'verificado',
    notes: 'Carátula oficial con entrada por mesa receptora INDERT central. Acompaña nómina de 10 familias censadas.',
  },
  {
    id: 'doc-indert-2',
    title: 'Resolución D.G. N° 1290/2025 - Admisión de Trámite de Colonización y Arraigo',
    category: 'expediente_indert',
    documentNumber: 'Res. INDERT 1290/25',
    date: '2025-06-18',
    uploadedBy: 'Carlos Mendoza (Presidente)',
    fileType: 'pdf',
    fileName: 'Resolucion_INDERT_Admision_Colonizacion.pdf',
    fileSize: '1.8 MB',
    status: 'verificado',
    notes: 'Resolución de la Junta Asesora y de Control que declara admisible la formación de la colonia agrícola-urbana.',
  },
  {
    id: 'doc-indert-3',
    title: 'Plano Topográfico Georreferenciado y Mensura Judicial (Coordenadas UTM)',
    category: 'mensura_planos',
    documentNumber: 'Plano UTM-WGS84-P14B',
    date: '2024-11-05',
    uploadedBy: 'Ing. Carlos Aranda (Agrimensor)',
    fileType: 'pdf',
    fileName: 'Plano_Georreferenciado_Sector16_Esperanza.pdf',
    fileSize: '4.8 MB',
    status: 'verificado',
    notes: 'Delimitación oficial de lotes, calles públicas de 12 metros y reserva para plaza comunal y pozo de agua.',
  },
  {
    id: 'doc-indert-4',
    title: 'Factura Contado N° 001-002-004812 - Compra de Cañerías PEAD y Accesorios Red de Agua',
    category: 'gastos_facturas',
    documentNumber: 'Factura 001-002-004812',
    amount: 620000,
    date: '2026-08-10',
    uploadedBy: 'Marta Delgado (Tesorera)',
    fileType: 'pdf',
    fileName: 'Factura_Tubos_Agua_SanRoque.pdf',
    fileSize: '1.2 MB',
    status: 'verificado',
    notes: 'Proveedora San Roque S.R.L. Materiales entregados en el pozo comunitario para conexión a Manzanas A y B.',
  },
  {
    id: 'doc-indert-5',
    title: 'Factura N° 002-001-009182 - Honorarios Profesionales de Agrimensura Judicial INDERT',
    category: 'gastos_facturas',
    documentNumber: 'Factura 002-001-009182',
    amount: 1450000,
    date: '2026-07-22',
    uploadedBy: 'Marta Delgado (Tesorera)',
    fileType: 'pdf',
    fileName: 'Factura_Topografo_Agrimensura_INDERT.pdf',
    fileSize: '950 KB',
    status: 'verificado',
    notes: 'Ing. Carlos Aranda - Colocación de mojones de cemento e informe técnico pericial para el INDERT.',
  },
  {
    id: 'doc-indert-6',
    title: 'Factura N° 001-003-001294 - Maquinaria y Nivelación de Caminos de Acceso Principal',
    category: 'gastos_facturas',
    documentNumber: 'Factura 001-003-001294',
    amount: 850000,
    date: '2026-08-25',
    uploadedBy: 'Marta Delgado (Tesorera)',
    fileType: 'pdf',
    fileName: 'Factura_Motoniveladora_VialSur.pdf',
    fileSize: '820 KB',
    status: 'verificado',
    notes: 'VialSur Servicios. 8 horas de motoniveladora y colocación de ripio en callejon de acceso comunal.',
  },
  {
    id: 'doc-indert-7',
    title: 'Acta N° 14 de Asamblea General de Pobladores - Rendición de Cuentas y Plan de Titulación',
    category: 'actas_asambleas',
    documentNumber: 'Acta 14/2026',
    date: '2026-08-30',
    uploadedBy: 'Carlos Mendoza (Presidente)',
    fileType: 'pdf',
    fileName: 'Acta_Asamblea_General_14_Agosto_2026.pdf',
    fileSize: '1.6 MB',
    status: 'verificado',
    notes: 'Aprobación unánime del balance de gastos de agua y ratificación de medidas contra especuladores de lotes.',
  },
  {
    id: 'doc-indert-8',
    title: 'Ficha de Ocupación, C.I. y Declaración Jurada Lote A-01 (Juan Bautista Benítez)',
    category: 'identidad_titulacion',
    documentNumber: 'Ocup-A01-INDERT',
    relatedBlock: 'A',
    relatedLot: '01',
    residentId: 'res-1',
    residentName: 'Juan Bautista Benítez',
    date: '2023-03-20',
    uploadedBy: 'Juan Bautista Benítez',
    fileType: 'pdf',
    fileName: 'Expediente_Lote_A01_Benitez_INDERT.pdf',
    fileSize: '2.3 MB',
    status: 'verificado',
    notes: 'Carpeta individual requerida por INDERT: Fotocopia de C.I., certificado de vida y residencia, y constancia de no poseer otros inmuebles.',
  },
  {
    id: 'doc-indert-9',
    title: 'Comprobante de Recaudación y Depósito Pro-Agua Potable Comunal',
    category: 'recibos_aportes',
    documentNumber: 'Boleta-BNF-89211',
    amount: 550000,
    date: '2026-09-02',
    uploadedBy: 'Marta Delgado (Tesorera)',
    fileType: 'pdf',
    fileName: 'Boleta_Deposito_Fondo_Agua_BNF.pdf',
    fileSize: '740 KB',
    status: 'verificado',
    notes: 'Depósito en cuenta BNF del comité vecinal correspondiente a aportes comunitarios.',
  },
];

export const initialLandRequests: LandRequest[] = [
  {
    id: 'req-1',
    applicantName: 'Ramón Estigarribia Gómez',
    documentId: '3.987.120',
    phone: '+595982334455',
    requestType: 'nuevo_lote',
    barrio: 'Sector 16',
    requestedBlock: 'C',
    requestedLot: '08',
    targetSector: 'Sector Norte - Hacia arroyo',
    requestDate: '2026-09-01',
    status: 'pendiente',
    familyMembersCount: 4,
    maritalStatus: 'casado',
    hasPartner: true,
    partnerName: 'Lorenza Galeano de Estigarribia',
    partnerDocumentId: '4.112.560',
    childrenCount: 2,
    hasChildrenWithDisability: false,
    documentFrontUrl: generateSampleCIDocument('Ramón Estigarribia Gómez', '3.987.120', 'frente'),
    documentBackUrl: generateSampleCIDocument('Ramón Estigarribia Gómez', '3.987.120', 'dorso'),
    decisionNotes: 'En evaluación en la directiva comunal. Postulante sin vivienda previa; verificado en lista comunitaria.',
  },
  {
    id: 'req-2',
    applicantName: 'Gladys Noemí Cáceres',
    documentId: '4.671.290',
    phone: '+595971998877',
    requestType: 'nuevo_lote',
    barrio: 'Sector 16',
    requestedBlock: 'B',
    requestedLot: '05',
    targetSector: 'Entrada Principal',
    requestDate: '2026-08-28',
    status: 'falta_documentos',
    familyMembersCount: 3,
    maritalStatus: 'concubinato',
    hasPartner: true,
    partnerName: 'Julio César Bogado',
    partnerDocumentId: '3.450.912',
    childrenCount: 2,
    hasChildrenWithDisability: true,
    disabilityDetails: 'Hijo menor de 6 años con movilidad reducida (requiere lote accesible cercano a la calle principal).',
    documentFrontUrl: generateSampleCIDocument('Gladys Noemí Cáceres', '4.671.290', 'frente'),
    missingDocumentsNotes: 'Falta fotocopia de C.I. Dorso de la pareja y Certificado de Vida y Residencia expedido por la comisaría.',
    decisionNotes: 'Se notificó por WhatsApp para que complete los documentos requeridos para la carpeta del INDERT.',
  },
  {
    id: 'req-3',
    applicantName: 'Marcos Antonio Duarte',
    documentId: '5.120.443',
    phone: '+595984667788',
    requestType: 'nuevo_lote',
    barrio: 'Sector 16',
    requestedBlock: 'A',
    requestedLot: '07',
    targetSector: 'Callejón Central',
    requestDate: '2026-08-15',
    status: 'aprobado',
    familyMembersCount: 5,
    maritalStatus: 'soltero',
    hasPartner: false,
    childrenCount: 3,
    hasChildrenWithDisability: false,
    assignedBlock: 'A',
    assignedLot: '07',
    documentFrontUrl: generateSampleCIDocument('Marcos Antonio Duarte', '5.120.443', 'frente'),
    documentBackUrl: generateSampleCIDocument('Marcos Antonio Duarte', '5.120.443', 'dorso'),
    decisionNotes: 'Aprobado por resolución de comisión vecinal del 25/08/2026. Cumple requisitos del estatuto comunal.',
    reviewedBy: 'Carlos Mendoza (Presidente)',
    reviewedAt: '2026-08-25',
  },
  {
    id: 'req-4',
    applicantName: 'Mirtha Benítez de Franco',
    documentId: '2.845.670',
    phone: '+595983776655',
    requestType: 'reubicacion',
    residentId: 'res-1',
    barrio: 'Sector 16',
    currentBlock: 'A',
    currentLot: '01',
    requestedBlock: 'B',
    requestedLot: '09',
    targetSector: 'Sector Alto Libre de Inundación',
    requestDate: '2026-08-20',
    status: 'pendiente',
    familyMembersCount: 4,
    maritalStatus: 'casado',
    childrenCount: 2,
    hasChildrenWithDisability: false,
    decisionNotes: 'Solicitud de reubicación por afectación de zanja pluvial natural en época de lluvias intensas.',
  },
  {
    id: 'req-5',
    applicantName: 'Esteban Bareiro Medina',
    documentId: '2.890.115',
    phone: '+595981002233',
    requestType: 'nuevo_lote',
    barrio: 'Sector 16',
    requestedBlock: 'C',
    requestedLot: '01',
    requestDate: '2026-08-10',
    status: 'denegado',
    familyMembersCount: 2,
    maritalStatus: 'soltero',
    decisionNotes: 'Denegado por la Comisión Vecinal: Antecedentes de comercialización irregular de parcela en asentamiento lindero.',
    reviewedBy: 'Carlos Mendoza (Presidente)',
    reviewedAt: '2026-08-14',
  },
];

export const initialCommunityPosts: CommunityPost[] = [
  {
    id: 'post-1',
    authorName: 'Carlos Mendoza Ramos',
    authorRole: 'Presidente Comisión INDERT',
    authorAvatarColor: 'bg-blue-800',
    date: 'Hoy a las 09:30 hs',
    badge: 'Resolución INDERT N° 842/2026',
    badgeType: 'indert',
    content:
      '¡Atención Vecinos del Sector 16!\n\nHemos recibido formalmente la Resolución N° 842 del INDERT que aprueba la continuidad de los trabajos técnicos y verificación del polígono para titulación social definitiva. Se adjunta el expediente digital para consulta vecinal.',
    attachedDocId: 'doc-indert-1',
    likes: 42,
    hasLiked: true,
    comments: [
      {
        id: 'c-1',
        userName: 'Juan Bautista Benítez',
        userRole: 'Residente Mz A - Lote 01',
        userBlockLot: 'Mz A - 01',
        text: 'Excelente gestión de la directiva. Ya pudimos amojonar con el topógrafo.',
        time: 'Hace 1 hora',
      },
      {
        id: 'c-2',
        userName: 'María Elena González',
        userRole: 'Residente Mz A - Lote 02',
        userBlockLot: 'Mz A - 02',
        text: '¡Muy buena noticia! Gracias por la transparencia.',
        time: 'Hace 30 min',
      },
    ],
  },
  {
    id: 'post-2',
    authorName: 'Marta Delgado Silva',
    authorRole: 'Tesorera Comisión Vecinal',
    authorAvatarColor: 'bg-emerald-600',
    date: 'Ayer a las 18:45 hs',
    badge: 'Rendición de Gastos de Red de Agua',
    badgeType: 'finances',
    content:
      'Rendición de cuentas comunal:\n\nSe ha cancelado en su totalidad la Factura N° 001-002-004812 correspondiente a la adquisición de cañerías PEAD y accesorios para la conexión de agua corriente comunitaria hacia las Manzanas A y B. Costo total: Gs. 620.000. Adjuntamos la factura digital para control vecinal.',
    attachedDocId: 'doc-indert-4',
    likes: 18,
    hasLiked: true,
    comments: [
      {
        id: 'c-3',
        userName: 'Ramón Centurión',
        userRole: 'Residente Mz B - Lote 04',
        userBlockLot: 'Mz B - 04',
        text: 'El agua ya llega con buena presión a nuestra manzana, gracias a todos los que pagaron puntuales.',
        time: 'Ayer',
      },
    ],
  },
  {
    id: 'post-3',
    authorName: 'Comisión Directiva y Delegados',
    authorRole: 'Convocatoria Oficial Comunitaria',
    authorAvatarColor: 'bg-amber-600',
    date: 'Hace 2 días',
    badge: 'Faena General de Limpieza',
    badgeType: 'shift',
    content:
      'CONVOCATORIA OBLIGATORIA A FAENA COMUNAL:\n\nEste sábado a las 08:00 hs realizaremos la limpieza de las zanjas de desagüe pluvial y corte de malezas del camino principal. Se recuerda que la participación activa en las faenas es requisito indispensable para la constancia de arraigo del INDERT.',
    likes: 31,
    hasLiked: false,
    comments: [],
  },
];


export const initialMeetings: import('../types').Meeting[] = [];
